#! /usr/bin/env python

from mp3_scripts.cli import entrypoint


def main():
    '''
    The main entry point for sesame CLI
    '''
    entrypoint()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit()
